development:
  clients:
    default:
      database: backend_development
      hosts:
        - mongo:27017
      options:
        server_selection_timeout: 1
test:
  clients:
    default:
      database: backend_test
      hosts:
        - mongo:27017
      options:
        server_selection_timeout: 1
production:
  clients:
    default:
      database: backend_production
      hosts:
        - mongo:27017
      options:
        server_selection_timeout: 1
